# Generated by Django 4.1 on 2022-08-11 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_list', models.CharField(max_length=100, verbose_name='category_list')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField(blank=True, null=True, verbose_name='app_id')),
                ('category', models.CharField(max_length=50)),
                ('korean_name', models.CharField(max_length=100)),
                ('english_name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
                ('thumbnail', models.ImageField(upload_to='')),
                ('allergy', models.CharField(max_length=30)),
                ('kcal', models.DecimalField(decimal_places=1, max_digits=5, null=True)),
                ('sodium_mg', models.DecimalField(decimal_places=1, max_digits=5, null=True)),
                ('saturated_fat_g', models.DecimalField(decimal_places=1, max_digits=5, null=True)),
                ('sugars_g', models.DecimalField(decimal_places=1, max_digits=5, null=True)),
                ('protein_g', models.DecimalField(decimal_places=1, max_digits=5, null=True)),
                ('caffeine_mg', models.DecimalField(decimal_places=1, max_digits=5, null=True)),
                ('size', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ['korean_name'],
            },
        ),
    ]
