# Generated by Django 4.1 on 2022-08-17 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0002_cafe_remove_product_digital_alter_product_cafe'),
        ('recommend', '0002_product_category'),
    ]

    operations = [
    ]
