# Generated by Django 4.1 on 2022-08-18 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0003_merge_20220817_1314'),
        ('recommend', '0003_merge_20220817_1717'),
    ]

    operations = [
    ]
