# Generated by Django 4.1 on 2022-08-07 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('korean_name', models.CharField(max_length=100)),
                ('english_name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infoapp.category')),
            ],
        ),
        migrations.CreateModel(
            name='Nutrition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('one_serving_kcal', models.DecimalField(decimal_places=1, max_digits=5, null=True)),
                ('sodium_mg', models.DecimalField(decimal_places=1, max_digits=5, null=True)),
                ('saturated_fat_g', models.DecimalField(decimal_places=1, max_digits=5, null=True)),
                ('sugars_g', models.DecimalField(decimal_places=1, max_digits=5, null=True)),
                ('protein_g', models.DecimalField(decimal_places=1, max_digits=5, null=True)),
                ('caffeine_mg', models.DecimalField(decimal_places=1, max_digits=5, null=True)),
                ('size', models.CharField(max_length=30)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='infoapp.product')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(max_length=2000)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infoapp.product')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infoapp.menu'),
        ),
        migrations.CreateModel(
            name='AllergyProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allergy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infoapp.allergy')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infoapp.product')),
            ],
        ),
        migrations.AddField(
            model_name='allergy',
            name='products',
            field=models.ManyToManyField(through='infoapp.AllergyProduct', to='infoapp.product'),
        ),
    ]
