# Generated by Django 4.1 on 2022-08-11 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infoapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='info_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info_list', models.CharField(max_length=100, verbose_name='info_list')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='product_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='app_id'),
        ),
    ]
