# Generated by Django 4.1 on 2022-08-19 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infoapp', '0003_company'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Company',
        ),
    ]
